// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProject.Data;

#nullable disable

namespace StudentProject.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20240115085955_addPasswordColumn")]
    partial class addPasswordColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentProject.Models.StudentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = "Mca",
                            Email = "saurabh@gmail.com",
                            FirstName = "Saurabh",
                            Gender = "Male",
                            LastName = "Sharma",
                            Password = "default",
                            Phone = "9834562398"
                        },
                        new
                        {
                            Id = 2,
                            Course = "Mca",
                            Email = "anita@gmail.com",
                            FirstName = "Anita",
                            Gender = "Female",
                            LastName = "Roy",
                            Password = "default",
                            Phone = "6754562398"
                        },
                        new
                        {
                            Id = 3,
                            Course = "Mca",
                            Email = "sarthak@gmail.com",
                            FirstName = "Sarthak",
                            Gender = "Male",
                            LastName = "Barman",
                            Password = "default",
                            Phone = "7834562398"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
